name = "FastTimm"
uuid = "6fe279a3-76fd-4f59-807e-d8e68e6f60cf"
authors = ["lorenzoh <lorenz.ohly@gmail.com> and contributors"]
version = "0.1.0"

[deps]
FastAI = "5d0beca9-ade8-49ae-ad0b-a3cf890e669f"
FastVision = "7bf02486-ff4c-4e73-b158-40c00866b54f"
Metalhead = "dbeba491-748d-5e0e-a39e-b530a07fa0cc"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyNNTraining = "013e1a4a-88fe-473f-be94-6c6af62e62ad"

[compat]
PyCall = "1"
julia = "1.8"
